### ISSUE TITLE
Null Date of First Planned Payment 

### ISSUE THREAD

**Issue by therajanmaurya** [mifosio/portfolio#45]
while fetching the Planned payment, first planned payment date is always null.

**Comment by myrle-krantz** [comment]
This is because the first entry in the planned payments is actually the initial disbursal.  If you wish to discuss changing this please re-enter this issue in the Apache jira:

https://issues.apache.org/jira/projects/FINCN/issues/FINCN-10?filter=allopenissues

I'm closing this issue here because there is no active development on the mifosio repository and I hope that it will be deleted soon.
